# Generated by Django 4.0 on 2022-05-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HSAdmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=200)),
                ('highschool', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
            ],
        ),
    ]
